const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2348165846414",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "false",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0V0NTB5NVZFVmR6V0JHWHI2WEhLS0N0WThmZUJqKzlvMElKV1p5Z0NHRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibVZLb1U0OWk1d3JqZWZZTlhHcE9PNFlDYWt2SG5vVnlMaVRjTUdKL1pHWT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzQXJCWWlXOHZnZ09KZ1lCVlJuQkdTcjR1ejRZamVFYnZ4RlNVbGJkbFhZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJOZEVNa1Uyb3duWU9RcmxzNjQ3eEQyTC9GMEdnWFRjRERqcnRuSFQ1dTNBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBLanVQMjZCMmxkeU9nU05VWVNDd0ZOb1doS2JacGtoYmczbFpTNTRnWHc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlQyK2NPeFlKenNxRkF5bW43T0orYm1LeGtjdXlkMmRFRFZWVTRlTEw4Q289In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ08xRSt6VGdoRWx5N2M5VlRrT0FWdGZOeVBZbVBFSzVlbDYwbmJsR1ZWST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiendwWXp5ZGdUUjhYUWJ5UVoxbHdBdE9tYisrMG92RnArQmdMWnowOFZIcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ims0Yy9CUVN5YmFJTFZEVXRZQUNTeTRLQXhBSHBLaVAzVVJ3MWNIbDBiTng4MDJsYjhBNUtVem1adFp4bnJpUUNBUkoxVjhwWCtPRUZhNCtFVys2bkNBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTEyLCJhZHZTZWNyZXRLZXkiOiJzOXJsQmtNTkFGNUg4SCtsa3NUbk1UWDh6NGNnMWZEQ2lGNmR2Q1NaeWxRPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJZNUFTVlZBSyIsIm1lIjp7ImlkIjoiNTA5NDMwMDg3ODU6MzlAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiY2hhcmlzbWEgYm91dGlxdWUiLCJsaWQiOiIxNTk3MDg4Mjg3MTMxNjc6MzlAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKRDM1YjRGRU1qeHhyNEdHQWNnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJxU1IzT2VsZU1IQ0dQaThJZ25UOEo2V29PNGlocHY1Y2RwQS8zY1AwYjAwPSIsImFjY291bnRTaWduYXR1cmUiOiIyRTcwTUJuYm9YVk1nU1c0eU5vS0p5N2RaMkdJZld4L3lPMFdDVG1JcGNJV1NwL3FuSUV1aHJHOVdGMVFiTnJLbmhFbkdHYlZCQkU2N1NmNjl6bnlEZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoia1pjR2JZSVMvcXhrMExXdUE5NnJjZDZuYmVPUFNFR0szSFBvbnhIU1lHZkdhcEZiemVwVkdjT0NIZ0xlUVZIdVJUTUNSamk2YkkxUjdEcE80bStoQVE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI1MDk0MzAwODc4NTozOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJha2tkem5wWGpCd2hqNHZDSUowL0NlbHFEdUlvYWIrWEhhUVA5M0Q5RzlOIn19XSwicGxhdGZvcm0iOiJzbWJpIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQVVJQ0E9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NDE3OTc1ODgsImxhc3RQcm9wSGFzaCI6IjJHNEFtdSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSU12In0=",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
